FROM hadoopbase:latest

EXPOSE 8088 50070 50075 50030 50060

RUN apt-get update && \
    apt-get install -y \
    scala \
    python3 \
    python3-pip

RUN useradd hduser -m -s /bin/bash

WORKDIR /home/hduser

USER hduser

RUN wget https://downloads.apache.org/hadoop/common/hadoop-3.2.2/hadoop-3.2.2.tar.gz && \
    tar -xzf hadoop-3.2.2.tar.gz && \
    mv hadoop-3.2.2 hadoop && \
    rm *.gz
    
RUN wget https://downloads.apache.org/spark/spark-3.1.1/spark-3.1.1-bin-hadoop3.2.tgz && \
    tar xvzf spark-3.1.1-bin-hadoop3.2.tgz && \
    mv spark-3.1.1-bin-hadoop3.2 spark && \
    rm *.tgz

COPY config/shellrc /home/hduser/.bashrc
COPY config/shellrc /home/hduser/.profile

COPY config/hadoop-env.sh /home/hduser/
RUN cat /home/hduser/hadoop-env.sh >> /home/hduser/hadoop/etc/hadoop/hadoop-env.sh

COPY config/*xml /home/hduser/hadoop/etc/hadoop/

RUN mkdir -p /home/hduser/.ssh
COPY config/id_rsa* /home/hduser/.ssh/
COPY config/id_rsa.pub /home/hduser/.ssh/authorized_keys
COPY config/ssh_config .ssh/config

COPY config/hadoopcmd.sh hadoopcmd.sh

USER root
RUN chown -R hduser /home/hduser/.ssh /home/hduser/.bashrc \
          /home/hduser/.profile /home/hduser/hadoop-env.sh \
          /home/hduser/hadoopcmd.sh

RUN chmod 755 /home/hduser/hadoopcmd.sh

CMD service ssh start && sleep infinity
